version: '3.8'

services:
  frontend:
    image: frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: frontend
  
  backend:
    image: backend
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: backend
  
  training:
    image:  training
    build: ./ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    container_name: training

volumes:
  imgs:
  model: