FROM ubuntu:focal

WORKDIR /usr/src/app

# To connect to the backend as required in Ex1.14
ENV REACT_APP_BACKEND_URL="http://localhost:8080"

COPY . .

EXPOSE 5000

RUN apt update
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt install -y nodejs
RUN echo $(node -v)
RUN echo $(npm -v)
RUN npm install
RUN npm run build
RUN npm install -g serve
RUN useradd -m userapp
RUN chown userapp /usr/src/app

USER userapp

CMD ["serve", "-s", "-l", "5000", "build"]