version: '3.8'

services:
  example-frontend-alpine:
    image: example-frontend-alpine
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend-alpine
  
  example-backend-alpine:
    image: example-backend-alpine
    build: ./example-backend
    ports:
      - 8080:8080
    restart: unless-stopped
    container_name: example-backend-alpine
    environment:
      - REDIS_HOST=redis-container
      - POSTGRES_HOST=postgres-container
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  redis-container:
    image: redis:7.0.1
    command: redis-server
    restart: unless-stopped
    container_name: redis-container
    volumes:
      - cache:/data 
  
  postgres-container:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-container
    volumes:
        - database:/var/lib/postgresql/data

volumes:
  database:
  cache: