version: '3.8'

services:
  simple-web-service-browser:
    image: devopsdockeruh/simple-web-service:ubuntu
    build: .
    ports:
      - 8080:8080
    command: server
    container_name: simple-web-service-browser