version: '3.8'

services:
  example-frontend:
    image: ubuntu:focal
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend
  
  example-backend:
    image: golang:1.16
    build: ./example-backend
    ports:
      - 8080:8080
    container_name: example-backend